#!/usr/bin/env python

"""
Display all dbus desktop notifications in an aesthetically pleasing log.

Michael Fincham <michael.fincham@hotplate.co.nz>
"""

from __future__ import print_function

import time

import dbus
import dbus.mainloop.glib
import dbus.service
import gobject

class NotificationLog(dbus.service.Object):

    def __init__(self, *args, **kwargs):
        self.fake_id = 0
        self.date = ''
        super(NotificationLog, self).__init__(*args, **kwargs)

    @staticmethod
    def colour(foreground):
        return '\x1b[38;5;%dm' % foreground

    @staticmethod
    def character_sum(string):
        return sum([ord(c) for c in string])

    @dbus.service.method("org.freedesktop.Notifications", in_signature='susssasa{ss}i', out_signature='u')
    def Notify(self, app_name, notification_id, app_icon, summary, body, actions, hints, expire_timeout):
        if self.date != time.strftime('%Y-%m-%d'):
            timestamp = time.strftime('%Y-%m-%d %H:%M:%S')
            self.date = time.strftime('%Y-%m-%d')
        else:
            timestamp = time.strftime('%H:%M:%S')

        if notification_id is None:
            self.fake_id += 1
            notification_id = self.fake_id

        app_colour = self.character_sum(app_name) % 14 + 1
        if app_colour == 7 or app_colour == 15:
            app_colour = app_colour - 1

        print("%s%s %s%s%s" % (self.colour(7), timestamp, self.colour(app_colour), summary, self.colour(15)))
        if len(strip(bodu)):
            print(body.rjust(len(timestamp) + len(body) + 1))
        return notification_id

    @dbus.service.method("org.freedesktop.Notifications", in_signature='', out_signature='as')
    def GetCapabilities(self):
        return ("body")

    @dbus.service.signal('org.freedesktop.Notifications', signature='uu')
    def NotificationClosed(self, id_in, reason_in):
        pass

    @dbus.service.method("org.freedesktop.Notifications", in_signature='u', out_signature='')
    def CloseNotification(self, id):
        pass

    @dbus.service.method("org.freedesktop.Notifications", in_signature='', out_signature='ssss')
    def GetServerInformation(self):
      return ("notifylog", "", "0", "1")

if __name__ == '__main__':
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
    session_bus = dbus.SessionBus()
    name = dbus.service.BusName("org.freedesktop.Notifications", session_bus)
    nf = NotificationLog(session_bus, '/org/freedesktop/Notifications')
    context = gobject.MainLoop().get_context()

    while 1:
        context.iteration(True)

